### ISSUE TITLE
[FEATURE] Change Proximity Result Display

### ISSUE THREAD

**Issue by Gavin-Qiao** [ZhuoQiuMcgill/CVT#2]
## Is your feature request related to a problem? Please describe.
Currently, the application uses a light indicator to display proximity results. While effective, this method may not be the most intuitive or visually accessible for all users.

## Describe the solution you'd like
1. I propose we change the proximity result display from a light indicator to using background colours. This could potentially improve user experience by providing a more easily recognizable visual cue.

2. Replace the light indicator with contrast background colour changes to represent different proximity results and use intuitive colour coding (e.g., light green for "passed," pink red for "failed").

**Comment by ZhuoQiuMcgill** [comment]
Completed
