### ISSUE TITLE
[FEATURE] Navigate to Frames Where Clicked Point is a Reference Point

### ISSUE THREAD

**Issue by Gavin-Qiao** [ZhuoQiuMcgill/CVT#3]
## Description:
It would be a valuable addition to the tool to have the capability to easily navigate to any frame where a selected point serves as a reference point. Currently, it's cumbersome to manually search for frames where a particular point is used as a reference point.

## Acceptance Criteria:
1. The user clicks on a point in the plot.
2. A UI element appears, listing all the frames where the point is a reference (or listing all in a text area).
3. (Optional) Clicking on a frame number in the list navigates the user to that specific frame.

**Comment by ZhuoQiuMcgill** [comment]
done
