### ISSUE TITLE
[IMPROVEMENT] Extend Adjustable Point Radius from 1-10 to 1-20

### ISSUE THREAD

**Issue by Gavin-Qiao** [ZhuoQiuMcgill/CVT#4]
## Description:
Currently, the point radius in our visualization tool can only be adjusted between 1 and 10. Due to the recent change that _**all datasets will be min-max normalized to fit into a 1-sized box**_, the current range is inadequate for proper visualization. This feature request aims to extend the adjustable point radius from a range of 1-10 to 1-20.

## Proposed Feature:
1. Extend the current point radius adjustment range from 1-10 to 1-20.
2. Update the UI slider (or other control elements) to reflect this new range.

## Additional Information:
1. This request is to ensure that users can properly visualize min-max normalized datasets.
2. The canvas can have a fixed initial size.

## Acceptance Criteria:
1. The user can adjust the point radius between 1 and 20 via the UI.
2. In the first frame, the canvas is also a 1-sized box in the coordinate system.

**Comment by ZhuoQiuMcgill** [comment]
completed
