### ISSUE TITLE
[FEATURE] New Visualization Tool with Essentials from Existing Tool and Additional Functionalities

### ISSUE THREAD

**Issue by Gavin-Qiao** [ZhuoQiuMcgill/CVT#5]
## Description:
This feature request is for the creation of a brand-new visualization tool. The new tool should incorporate the essential features of the existing tool, such as file import, user navigation, and basic UI while introducing new functionalities like an erase brush and frontend statistical analysis capabilities.

## Use-case:
1. **File Import and Basic UI**: Retain these essential features to maintain continuity with the existing tool and offer a familiar user experience.

2. **Erase Brush**: Allow users the ability to erase specific data points or clusters directly from the canvas, affecting both the visual representation and the underlying data structure.

3. **Frontend Statistical Algorithms**: Provide users with the capability to run statistical algorithms on the remaining points in the canvas, directly from the frontend.

## Proposed Features:
1. **File Import, User Navigation, and Basic UI**: These features should be carried over from the existing tool.

2. **Erase Brush Functionality**:
- Implement an erase brush feature in the UI.
- Ensure that erased points are removed from both the canvas and the internal data structure.

3. **Frontend Statistical Analysis**:
- Leave a frontend port for statistics (port output: array of points. port input: result in HTML)
- The results of the analysis should be displayed in a user-friendly manner, directly within the tool's frontend.

## Acceptance Criteria:
**TBD**

**Comment by ZhuoQiuMcgill** [comment]
done
